"""Targeted semantic mutation check for the Actseal gate (v1 Task 04).

Eight prescribed mutations of the statistical gate are applied one at a time
to *temporary copies* of the package and test tree; tracked source is never
modified. A mutant counts as killed only when every designated test fails in
its **call phase with ``AssertionError``** in a fresh interpreter whose
``actseal`` imports resolve to the temporary tree. Import, setup or lint
errors, timeouts, signals, skips, xfails and unexpected exception types never
count as kills: they invalidate the mutant.

Harness gates, in order:

1. the designated tests run unchanged against an unmutated temporary copy and
   must all pass (a baseline compile/import/setup/no-test/skip/xfail problem is
   a harness ERROR, exit 2);
2. each mutant must match exactly one anchor in exactly one file and change
   the file's bytes (reported with SHA-256 before/after);
3. a fresh subprocess probe reports the module paths it imported, the
   implementation fingerprint of the mutated tree, and that a lock sealed
   under that identity validates (locks are regenerated by the tests under the
   mutant source identity with validation enabled);
4. the designated tests run with a probe plugin that records every node's
   setup/call/teardown outcome and exception type.

Any survivor, invalid or unexecuted mutant makes the exit status nonzero.
Lint/type checks apply to the real sources only; mutants are never linted.

Temporary-tree ownership: ``--workdir`` names an existing *parent* directory
(default: the system temporary directory). It is resolved (symlinks, ``..``)
and refused when it is, or lies beneath, ``src/actseal`` or ``tests``. The run
creates one uniquely named child beneath it and removes only that child;
``--keep`` retains the child. Symlinks among the copied inputs are refused
before any copy so ``copytree`` can neither follow an external link nor
recurse.

Usage::

    uv run --frozen python tools/check_mutations.py [--only M01 ...] [--json PATH] [--keep]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
COPIED_DIRS = ("src/actseal", "tests")
COPIED_FILES = ("pyproject.toml",)
IGNORED = shutil.ignore_patterns("__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache")
PLUGIN_NAME = "actseal_mutation_probe"
PROBE_ENV = "ACTSEAL_MUTATION_PROBE"
ACTSEAL_MODULES = ("actseal", "actseal.assessment", "actseal.policy", "actseal.stats")
EXIT_OK = 0
EXIT_NOT_KILLED = 1
EXIT_HARNESS_ERROR = 2
PYTEST_EXIT_TESTS_FAILED = 1
TAIL_CHARS = 2000

ASSESSMENT = "src/actseal/assessment.py"
POLICY = "src/actseal/policy.py"
T_ASSESSMENT = "tests/unit/test_assessment.py"
T_POLICY = "tests/unit/test_policy.py"
T_GATE = "tests/properties/test_gate_properties.py"


@dataclass(frozen=True)
class Mutant:
    """One prescribed semantic mutation and the tests designated to kill it."""

    mutant_id: str
    title: str
    file: str
    anchor: str
    replacement: str
    #: Node ids to run (function-level ids run every parametrization).
    tests: tuple[str, ...]
    #: Node ids that must fail with a call-phase AssertionError. A function-level
    #: id means every collected parametrization of that function must fail.
    expected_failures: tuple[str, ...]


MUTANTS: tuple[Mutant, ...] = (
    Mutant(
        "M01",
        "tail allocation: TAIL_DIVISOR 4 -> 2 (alpha/2 per tail instead of alpha/4)",
        ASSESSMENT,
        "TAIL_DIVISOR: Final = 4",
        "TAIL_DIVISOR: Final = 2",
        (
            f"{T_ASSESSMENT}::test_alpha_quarter_is_the_tail_for_each_interval",
            f"{T_GATE}::test_alpha_quarter_endpoints_match_the_decimal_oracle_at_alpha_point_two",
        ),
        (
            f"{T_ASSESSMENT}::test_alpha_quarter_is_the_tail_for_each_interval",
            f"{T_GATE}::test_alpha_quarter_endpoints_match_the_decimal_oracle_at_alpha_point_two",
        ),
    ),
    Mutant(
        "M02",
        "scheduled denominator: n = len(lock.verification_cases) -> n = accepted",
        ASSESSMENT,
        "    return len(lock.verification_cases), accepted, errors\n",
        "    return accepted, accepted, errors\n",
        (f"{T_ASSESSMENT}::test_denominator_counts_every_scheduled_case_and_only_final_acts",),
        (f"{T_ASSESSMENT}::test_denominator_counts_every_scheduled_case_and_only_final_acts",),
    ),
    Mutant(
        "M03",
        "zero-accepted handling: risk [0, 1] -> [0, 0] when a == 0",
        ASSESSMENT,
        "    risk = _FULL if accepted == 0 else clopper_pearson_tail(errors, accepted, tail)\n",
        (
            "    risk = (0.0, 0.0) if accepted == 0 "
            "else clopper_pearson_tail(errors, accepted, tail)\n"
        ),
        (f"{T_ASSESSMENT}::test_no_accepted_cases_use_full_risk_and_cannot_pass",),
        (f"{T_ASSESSMENT}::test_no_accepted_cases_use_full_risk_and_cannot_pass",),
    ),
    Mutant(
        "M04",
        "threshold boundary: selected_probability < threshold -> <= (equality abstains)",
        POLICY,
        "    if outcome.selected_probability < policy.threshold:\n",
        "    if outcome.selected_probability <= policy.threshold:\n",
        (
            f"{T_POLICY}::test_threshold_equality_is_act_and_anything_below_abstains",
            f"{T_GATE}::test_generated_thresholds_act_at_equality_and_abstain_one_ulp_below",
        ),
        (
            f"{T_POLICY}::test_threshold_equality_is_act_and_anything_below_abstains[0.9-0.9-ACT]",
            f"{T_POLICY}::test_threshold_equality_is_act_and_anything_below_abstains[1.0-1.0-ACT]",
            (
                f"{T_POLICY}::test_threshold_equality_is_act_and_anything_below_abstains"
                "[1e-300-1e-300-ACT]"
            ),
            (
                f"{T_POLICY}::test_threshold_equality_is_act_and_anything_below_abstains"
                "[5e-324-5e-324-ACT]"
            ),
            f"{T_POLICY}::test_threshold_equality_is_act_and_anything_below_abstains[0.5-0.5-ACT]",
            f"{T_GATE}::test_generated_thresholds_act_at_equality_and_abstain_one_ulp_below",
        ),
    ),
    Mutant(
        "M05",
        "risk-bound selection: PASS tests risk.lower instead of risk.upper",
        ASSESSMENT,
        "risk[1] <= limits.max_risk",
        "risk[0] <= limits.max_risk",
        (f"{T_GATE}::test_pass_requires_the_risk_upper_bound_not_the_lower_bound",),
        (f"{T_GATE}::test_pass_requires_the_risk_upper_bound_not_the_lower_bound",),
    ),
    Mutant(
        "M06",
        "coverage-bound selection: PASS tests coverage.upper instead of coverage.lower",
        ASSESSMENT,
        "coverage[0] >= limits.min_coverage",
        "coverage[1] >= limits.min_coverage",
        (f"{T_GATE}::test_pass_requires_the_coverage_lower_bound_not_the_upper_bound",),
        (f"{T_GATE}::test_pass_requires_the_coverage_lower_bound_not_the_upper_bound",),
    ),
    Mutant(
        "M07",
        "fault blocking: violations = _fault_violations(...) -> set() (faults never block)",
        ASSESSMENT,
        "    violations = _fault_violations(typed_faults, lock)\n",
        "    violations = set()\n",
        (f"{T_ASSESSMENT}::test_every_fault_action_mismatch_blocks",),
        (f"{T_ASSESSMENT}::test_every_fault_action_mismatch_blocks",),
    ),
    Mutant(
        "M08",
        "ERROR precedence: integrity failures ignored when a fault violation is present",
        ASSESSMENT,
        "    if failures:\n        return _error(lock, failures)\n",
        "    if failures and not _fault_violations(typed_faults, lock):\n"
        "        return _error(lock, failures)\n",
        (f"{T_GATE}::test_integrity_failure_outranks_a_reproducible_fault_violation",),
        (f"{T_GATE}::test_integrity_failure_outranks_a_reproducible_fault_violation",),
    ),
)


PLUGIN_SOURCE = f'''"""Probe plugin: module paths and every test phase outcome as JSON lines."""
import json
import os
import sys

import pytest

_PATH = os.environ[{PROBE_ENV!r}]


def _write(record):
    with open(_PATH, "a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, sort_keys=True) + "\\n")


def pytest_sessionstart(session):
    import actseal.assessment
    import actseal.policy
    import actseal.stats
    from actseal.serialization import implementation_fingerprint

    modules = {{name: sys.modules[name].__file__ for name in {ACTSEAL_MODULES!r}}}
    _write({{"event": "session", "modules": modules, "fingerprint": implementation_fingerprint(),
             "cwd": os.getcwd(), "executable": sys.executable}})


def pytest_collection_finish(session):
    _write({{"event": "collected", "nodeids": [item.nodeid for item in session.items]}})


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    record = {{"event": "report", "nodeid": report.nodeid, "when": report.when,
              "outcome": report.outcome, "wasxfail": hasattr(report, "wasxfail")}}
    if call.excinfo is not None:
        record["exception"] = call.excinfo.type.__name__
        record["exception_module"] = call.excinfo.type.__module__
        text = str(call.excinfo.value)
        record["message"] = text.splitlines()[0][:300] if text else ""
    _write(record)
'''


PROBE_SCRIPT = """
import json
import sys

import actseal
import actseal.assessment
import actseal.policy
import actseal.stats
from actseal.locking import create_lock, validate_lock
from actseal.records import (
    ChoiceQuestion,
    Contract,
    GateLimits,
    LockedPolicy,
    ModelIdentity,
    Option,
)
from actseal.serialization import implementation_fingerprint

labels = ("billing", "technical", "sales")
question = ChoiceQuestion(
    "department",
    "Select the department responsible for this ticket.",
    (Option("billing", "Payments"), Option("technical", "Technical"), Option("sales", "Sales")),
)
contract = Contract(
    1,
    "mutation-probe",
    question,
    LockedPolicy(labels, labels, 0.9),
    GateLimits(0.05, 0.5, 0.05),
    "demo",
    "Mutation harness probe; no deployment claim",
)
identity = ModelIdentity(
    "fixture", "recorded-choice-v1", "a" * 64, (("responses", "a" * 64),), "1", "1",
    (("python", "3.12"),),
)
calibration = '{"case_id": "c-001", "state": "Calibration one.", "expected_label": "billing"}\\n'
verification = (
    '{"case_id": "v-001", "state": "Refund missing after cancellation.", '
    '"expected_label": "billing"}\\n'
)
lock = create_lock(contract, calibration, verification, identity)
validate_lock(lock)
modules = {name: sys.modules[name].__file__ for name in __MODULES__}
print(json.dumps({
    "modules": modules,
    "fingerprint": implementation_fingerprint(),
    "lock_implementation_sha256": lock.implementation_sha256,
    "lock_sha256": lock.sha256,
    "validated": True,
}))
""".replace("__MODULES__", repr(ACTSEAL_MODULES))


# --------------------------------------------------------------------------- #
# Results
# --------------------------------------------------------------------------- #


@dataclass
class NodeOutcome:
    nodeid: str
    phases: dict[str, str] = field(default_factory=dict)
    exception: str | None = None
    exception_module: str | None = None
    message: str = ""
    wasxfail: bool = False

    @property
    def assertion_failed_in_call(self) -> bool:
        return (
            self.phases.get("call") == "failed"
            and self.exception == "AssertionError"
            and self.exception_module == "builtins"
        )


@dataclass
class PytestRun:
    command: str
    returncode: int | None
    duration: float
    timed_out: bool
    stdout_tail: str
    stderr_tail: str
    session: dict[str, object]
    collected: list[str]
    nodes: dict[str, NodeOutcome]
    problems: list[str] = field(default_factory=list)


@dataclass
class ProbeResult:
    command: str
    ok: bool
    data: dict[str, object]
    problems: list[str]


@dataclass
class MutantResult:
    mutant: Mutant
    status: str  # KILLED / SURVIVED / INVALID / UNEXECUTED
    notes: list[str] = field(default_factory=list)
    original_sha256: str = ""
    mutated_sha256: str = ""
    anchor_count: int = 0
    probe: ProbeResult | None = None
    run: PytestRun | None = None
    assertion_failures: list[str] = field(default_factory=list)
    expected_failures: list[str] = field(default_factory=list)


class HarnessError(Exception):
    """A gate of the harness itself failed; no mutant verdict is meaningful."""


# --------------------------------------------------------------------------- #
# Tree preparation
# --------------------------------------------------------------------------- #


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


IGNORED_PARTS = frozenset({"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"})
WORKDIR_PREFIX = "actseal-mutants-"


def copied_files(repo: Path) -> list[Path]:
    """Every regular file the harness copies, walking without following links."""
    files: list[Path] = []
    for relative in COPIED_DIRS:
        for dirpath, dirnames, filenames in os.walk(repo / relative, followlinks=False):
            dirnames[:] = sorted(name for name in dirnames if name not in IGNORED_PARTS)
            files.extend(Path(dirpath) / name for name in sorted(filenames))
    files.extend(repo / relative for relative in COPIED_FILES)
    return files


def refuse_symlinks(repo: Path) -> None:
    """Reject any symlink among the copied inputs so a copy can never follow a link.

    Ignored cache directories are skipped. A symlinked copied directory or file,
    a symlinked subdirectory or a symlinked file anywhere beneath ``src/actseal``
    or ``tests`` is a harness error: ``copytree`` would otherwise read an
    external target or recurse into a loop.
    """
    for relative in (*COPIED_DIRS, *COPIED_FILES):
        root = repo / relative
        if root.is_symlink():
            raise HarnessError(f"copied input is a symlink: {relative}")
        if not root.exists():
            raise HarnessError(f"copied input is missing: {relative}")
    for relative in COPIED_DIRS:
        for dirpath, dirnames, filenames in os.walk(repo / relative, followlinks=False):
            dirnames[:] = [name for name in dirnames if name not in IGNORED_PARTS]
            for name in (*dirnames, *filenames):
                candidate = Path(dirpath) / name
                if candidate.is_symlink():
                    shown = candidate.relative_to(repo).as_posix()
                    raise HarnessError(f"symlink inside copied inputs: {shown}")


def tracked_source_digest(repo: Path = REPO) -> dict[str, str]:
    """SHA-256 of every file the harness copies, to prove the repository is untouched."""
    return {path.relative_to(repo).as_posix(): sha256_file(path) for path in copied_files(repo)}


def safe_parent(parent: Path, repo: Path = REPO) -> Path:
    """Resolve an existing parent directory and refuse one inside the copied sources.

    Symlinks and ``..`` are resolved first so an alias of ``src/actseal`` or
    ``tests`` is rejected while a resolved alias of a safe directory (for
    example a symlinked temporary root) stays valid.
    """
    if parent.is_symlink() and not parent.exists():
        raise HarnessError(f"workdir parent is a dangling symlink: {parent}")
    if not parent.is_dir():
        raise HarnessError(f"workdir parent must be an existing directory: {parent}")
    resolved = parent.resolve(strict=True)
    for relative in COPIED_DIRS:
        protected = (repo / relative).resolve()
        if resolved == protected or protected in resolved.parents:
            raise HarnessError(f"workdir parent {resolved} lies inside copied source {relative}")
    return resolved


def allocate_workdir(parent: Path | None, repo: Path = REPO) -> Path:
    """Create a uniquely named child the harness owns beneath a checked parent."""
    base = safe_parent(parent if parent is not None else Path(tempfile.gettempdir()), repo)
    return Path(tempfile.mkdtemp(prefix=WORKDIR_PREFIX, dir=base))


def release_workdir(workdir: Path, *, keep: bool) -> None:
    """Remove only the child this run created; the caller's parent is never touched."""
    if keep:
        emit(f"temporary trees kept under {workdir}")
        return
    if workdir.is_symlink() or not workdir.name.startswith(WORKDIR_PREFIX):
        raise HarnessError(f"refusing to remove a directory the harness did not create: {workdir}")
    shutil.rmtree(workdir, ignore_errors=True)


def run_in_owned_workdir(
    parent: Path | None, *, keep: bool, repo: Path, body: Callable[[Path], int]
) -> int:
    """Allocate an owned child, run ``body`` in it and release only that child."""
    workdir = allocate_workdir(parent, repo)
    try:
        return body(workdir)
    finally:
        release_workdir(workdir, keep=keep)


def make_tree(workdir: Path, name: str, repo: Path = REPO) -> Path:
    """Copy the package, tests and pytest configuration into ``workdir/name``."""
    refuse_symlinks(repo)
    tree = workdir / name
    for relative in COPIED_DIRS:
        shutil.copytree(repo / relative, tree / relative, ignore=IGNORED)
    for relative in COPIED_FILES:
        shutil.copy2(repo / relative, tree / relative)
    (tree / f"{PLUGIN_NAME}.py").write_text(PLUGIN_SOURCE, encoding="utf-8")
    for relative, expected in tracked_source_digest(repo).items():
        copied = tree / relative
        if not copied.is_file() or sha256_file(copied) != expected:
            raise HarnessError(f"copy of {relative} does not match the repository")
    return tree


def apply_mutation(tree: Path, mutant: Mutant, result: MutantResult) -> None:
    """Replace exactly one anchor in exactly one file; anything else invalidates."""
    target = tree / mutant.file
    original = target.read_bytes()
    result.original_sha256 = hashlib.sha256(original).hexdigest()
    anchor = mutant.anchor.encode("utf-8")
    result.anchor_count = original.count(anchor)
    if result.anchor_count != 1:
        raise HarnessError(f"anchor matched {result.anchor_count} times in {mutant.file}, need 1")
    mutated = original.replace(anchor, mutant.replacement.encode("utf-8"), 1)
    if mutated == original:
        raise HarnessError(f"mutation left {mutant.file} byte-identical")
    target.write_bytes(mutated)
    result.mutated_sha256 = hashlib.sha256(mutated).hexdigest()
    changed = [
        relative
        for relative, expected in tracked_source_digest().items()
        if sha256_file(tree / relative) != expected
    ]
    if changed != [mutant.file]:
        raise HarnessError(f"mutant changed files {changed}, expected [{mutant.file!r}]")


def child_env(tree: Path, probe_path: Path | None = None) -> dict[str, str]:
    env = dict(os.environ)
    env["PYTHONPATH"] = f"{tree / 'src'}{os.pathsep}{tree}"
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env.pop("PYTEST_ADDOPTS", None)
    if probe_path is not None:
        env[PROBE_ENV] = str(probe_path)
    return env


# --------------------------------------------------------------------------- #
# Fresh-import probe
# --------------------------------------------------------------------------- #


def run_probe(tree: Path, *, timeout: float) -> ProbeResult:
    command = [sys.executable, "-c", PROBE_SCRIPT]
    shown = shlex.join([sys.executable, "-c", "<probe script>"])
    problems: list[str] = []
    try:
        completed = subprocess.run(  # noqa: S603 - fixed interpreter and literal script
            command,
            cwd=tree,
            env=child_env(tree),
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return ProbeResult(command=shown, ok=False, data={}, problems=["probe timed out"])
    if completed.returncode != 0:
        problems.append(f"probe exit {completed.returncode}: {completed.stderr[-TAIL_CHARS:]}")
        return ProbeResult(command=shown, ok=False, data={}, problems=problems)
    try:
        raw = json.loads(completed.stdout.strip().splitlines()[-1])
    except (ValueError, IndexError) as error:
        problems.append(f"probe output unreadable: {error}")
        return ProbeResult(command=shown, ok=False, data={}, problems=problems)
    data: dict[str, object] = dict(raw) if isinstance(raw, dict) else {}
    modules = data.get("modules")
    if not isinstance(modules, dict):
        problems.append("probe reported no module paths")
    else:
        problems.extend(check_module_paths(tree, modules))
    if data.get("fingerprint") != data.get("lock_implementation_sha256"):
        problems.append("regenerated lock does not carry the tree's fingerprint")
    if data.get("validated") is not True:
        problems.append("regenerated lock did not validate")
    return ProbeResult(command=shown, ok=not problems, data=data, problems=problems)


def check_module_paths(tree: Path, modules: Mapping[str, object]) -> list[str]:
    problems: list[str] = []
    src = (tree / "src").resolve()
    for name in ACTSEAL_MODULES:
        value = modules.get(name)
        if not isinstance(value, str):
            problems.append(f"{name}: no module path reported")
            continue
        resolved = Path(value).resolve()
        if src not in resolved.parents:
            problems.append(f"{name} imported from {value}, not from the temporary tree")
    return problems


# --------------------------------------------------------------------------- #
# Designated test run
# --------------------------------------------------------------------------- #


def run_pytest(tree: Path, nodeids: Sequence[str], *, timeout: float) -> PytestRun:
    probe_path = tree / "probe.jsonl"
    command = [
        sys.executable,
        "-m",
        "pytest",
        "-p",
        PLUGIN_NAME,
        "-p",
        "no:cacheprovider",
        "-q",
        "--no-header",
        *nodeids,
    ]
    shown = shlex.join(command)
    started = time.monotonic()
    try:
        completed = subprocess.run(  # noqa: S603 - fixed interpreter and literal node ids
            command,
            cwd=tree,
            env=child_env(tree, probe_path),
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired as expired:
        run = PytestRun(
            command=shown,
            returncode=None,
            duration=time.monotonic() - started,
            timed_out=True,
            stdout_tail=_tail(expired.stdout),
            stderr_tail=_tail(expired.stderr),
            session={},
            collected=[],
            nodes={},
        )
        run.problems.append(f"pytest timed out after {timeout:.0f}s")
        return run
    run = PytestRun(
        command=shown,
        returncode=completed.returncode,
        duration=time.monotonic() - started,
        timed_out=False,
        stdout_tail=completed.stdout[-TAIL_CHARS:],
        stderr_tail=completed.stderr[-TAIL_CHARS:],
        session={},
        collected=[],
        nodes={},
    )
    if probe_path.is_file():
        parse_probe_records(probe_path.read_text(encoding="utf-8"), run)
    else:
        run.problems.append("probe plugin wrote no records")
    if run.returncode not in (EXIT_OK, PYTEST_EXIT_TESTS_FAILED):
        run.problems.append(f"pytest exit {run.returncode} (usage/collection/internal error)")
    if not run.session:
        run.problems.append("no session record: plugin did not start")
    else:
        modules = run.session.get("modules")
        if isinstance(modules, dict):
            run.problems.extend(check_module_paths(tree, modules))
        else:
            run.problems.append("session record carries no module paths")
    if not run.collected:
        run.problems.append("no tests collected")
    return run


def _tail(value: str | bytes | None) -> str:
    if value is None:
        return ""
    text = value.decode("utf-8", "replace") if isinstance(value, bytes) else value
    return text[-TAIL_CHARS:]


def parse_probe_records(text: str, run: PytestRun) -> None:
    for line in text.splitlines():
        record = json.loads(line)
        event = record.get("event")
        if event == "session":
            run.session = dict(record)
        elif event == "collected":
            run.collected = [str(item) for item in record.get("nodeids", [])]
        elif event == "report":
            node = run.nodes.setdefault(record["nodeid"], NodeOutcome(record["nodeid"]))
            when = str(record["when"])
            node.phases[when] = str(record["outcome"])
            node.wasxfail = node.wasxfail or bool(record.get("wasxfail"))
            if "exception" in record and when == "call":
                node.exception = str(record["exception"])
                node.exception_module = str(record.get("exception_module", ""))
                node.message = str(record.get("message", ""))
            elif "exception" in record and node.exception is None:
                node.exception = f"{record['exception']} during {when}"
                node.exception_module = str(record.get("exception_module", ""))
                node.message = str(record.get("message", ""))


def expand_expected(
    expected: Iterable[str], collected: Sequence[str]
) -> tuple[list[str], list[str]]:
    """Expand function-level ids to every collected parametrization; report missing ids."""
    expanded: list[str] = []
    missing: list[str] = []
    for nodeid in expected:
        if nodeid in collected:
            expanded.append(nodeid)
            continue
        matches = [item for item in collected if item.startswith(f"{nodeid}[")]
        if matches:
            expanded.extend(matches)
        else:
            missing.append(nodeid)
    return expanded, missing


def node_problems(node: NodeOutcome) -> list[str]:
    """Anything other than passed/passed/passed or a clean call-phase AssertionError."""
    problems: list[str] = []
    for phase in ("setup", "teardown"):
        outcome = node.phases.get(phase)
        if outcome != "passed":
            problems.append(f"{node.nodeid}: {phase} {outcome or 'missing'} ({node.message})")
    call = node.phases.get("call")
    if call is None:
        problems.append(f"{node.nodeid}: no call phase")
    elif call == "skipped" or node.wasxfail:
        problems.append(f"{node.nodeid}: skipped/xfail is not a kill")
    elif call == "failed" and not node.assertion_failed_in_call:
        problems.append(
            f"{node.nodeid}: call raised {node.exception_module}.{node.exception}: {node.message}"
        )
    return problems


# --------------------------------------------------------------------------- #
# Gates
# --------------------------------------------------------------------------- #


def all_designated_tests(mutants: Sequence[Mutant]) -> list[str]:
    seen: dict[str, None] = {}
    for mutant in mutants:
        for nodeid in mutant.tests:
            seen.setdefault(nodeid, None)
    return list(seen)


def check_baseline(run: PytestRun, mutants: Sequence[Mutant]) -> list[str]:
    """Every designated node must exist and pass in every phase on the unmutated copy."""
    problems = list(run.problems)
    if run.returncode != EXIT_OK:
        problems.append(f"baseline pytest exit {run.returncode}, expected 0")
    for mutant in mutants:
        _, missing_tests = expand_expected(mutant.tests, run.collected)
        _, missing_expected = expand_expected(mutant.expected_failures, run.collected)
        problems.extend(
            f"{mutant.mutant_id}: designated node not collected: {nodeid}"
            for nodeid in (*missing_tests, *missing_expected)
        )
    for nodeid in run.collected:
        node = run.nodes.get(nodeid)
        if node is None:
            problems.append(f"{nodeid}: no phase reports")
            continue
        problems.extend(node_problems(node))
        if node.phases.get("call") != "passed":
            problems.append(f"{nodeid}: baseline call {node.phases.get('call')}")
    return problems


def classify(result: MutantResult) -> None:
    run = result.run
    if run is None:
        result.status = "UNEXECUTED"
        return
    notes = list(run.problems)
    expected, missing = expand_expected(result.mutant.expected_failures, run.collected)
    result.expected_failures = expected
    notes.extend(f"expected node not collected: {nodeid}" for nodeid in missing)
    for nodeid in run.collected:
        node = run.nodes.get(nodeid)
        if node is None:
            notes.append(f"{nodeid}: no phase reports")
            continue
        notes.extend(node_problems(node))
        if node.assertion_failed_in_call:
            result.assertion_failures.append(nodeid)
    if result.probe is not None and not result.probe.ok:
        notes.extend(result.probe.problems)
    if notes:
        result.status = "INVALID"
        result.notes.extend(notes)
        return
    if not result.assertion_failures:
        result.status = "SURVIVED"
        result.notes.append("every designated test passed against the mutant")
        return
    survived = [nodeid for nodeid in expected if nodeid not in result.assertion_failures]
    if survived:
        result.status = "INVALID"
        result.notes.append("expected failures did not occur: " + ", ".join(survived))
        return
    result.status = "KILLED"
    extra = [nodeid for nodeid in result.assertion_failures if nodeid not in expected]
    if extra:
        result.notes.append("additional call-phase assertion failures: " + ", ".join(extra))


def run_mutant(
    workdir: Path, mutant: Mutant, baseline_fingerprint: object, timeout: float
) -> MutantResult:
    result = MutantResult(mutant, "UNEXECUTED")
    try:
        tree = make_tree(workdir, mutant.mutant_id)
        apply_mutation(tree, mutant, result)
    except HarnessError as error:
        result.status = "INVALID"
        result.notes.append(str(error))
        return result
    result.probe = run_probe(tree, timeout=timeout)
    if result.probe.ok and result.probe.data.get("fingerprint") == baseline_fingerprint:
        result.probe.ok = False
        result.probe.problems.append("mutant fingerprint equals the baseline fingerprint")
    result.run = run_pytest(tree, mutant.tests, timeout=timeout)
    classify(result)
    return result


# --------------------------------------------------------------------------- #
# Reporting
# --------------------------------------------------------------------------- #


def emit(line: str = "") -> None:
    sys.stdout.write(line + "\n")


def report_run(run: PytestRun, *, indent: str = "  ") -> None:
    emit(f"{indent}command: {run.command}")
    status = "timed out" if run.timed_out else f"exit {run.returncode}"
    emit(f"{indent}pytest: {status} in {run.duration:.1f}s; collected {len(run.collected)} node(s)")
    modules = run.session.get("modules") if run.session else None
    if isinstance(modules, dict):
        for name, path in sorted(modules.items()):
            emit(f"{indent}  import {name} -> {path}")
    for nodeid in run.collected:
        node = run.nodes.get(nodeid)
        if node is None:
            emit(f"{indent}  {nodeid}: NO REPORT")
            continue
        phases = "/".join(node.phases.get(phase, "-") for phase in ("setup", "call", "teardown"))
        detail = ""
        if node.exception:
            detail = f" {node.exception_module}.{node.exception}: {node.message}"
        emit(f"{indent}  {nodeid}: {phases}{detail}")
    for problem in run.problems:
        emit(f"{indent}  problem: {problem}")
    if run.timed_out or run.returncode not in (EXIT_OK, PYTEST_EXIT_TESTS_FAILED):
        emit(f"{indent}  stdout tail: {run.stdout_tail.strip()[-600:]}")
        emit(f"{indent}  stderr tail: {run.stderr_tail.strip()[-600:]}")


def report_mutant(result: MutantResult) -> None:
    mutant = result.mutant
    emit(f"{mutant.mutant_id} {result.status}: {mutant.title}")
    emit(f"  file: {mutant.file}")
    emit(f"  anchor ({result.anchor_count} match): {mutant.anchor!r}")
    emit(f"  replacement: {mutant.replacement!r}")
    emit(f"  sha256 original: {result.original_sha256 or '-'}")
    emit(f"  sha256 mutated:  {result.mutated_sha256 or '-'}")
    if result.probe is not None:
        data = result.probe.data
        emit(f"  probe command: {result.probe.command}")
        emit(f"  probe fingerprint: {data.get('fingerprint', '-')}")
        emit(
            "  probe lock regenerated under mutant identity: "
            f"implementation_sha256={data.get('lock_implementation_sha256', '-')} "
            f"validated={data.get('validated', False)}"
        )
        for problem in result.probe.problems:
            emit(f"  probe problem: {problem}")
    emit(f"  expected call-phase AssertionError nodes ({len(result.expected_failures)}):")
    for nodeid in result.expected_failures:
        emit(f"    {nodeid}")
    if result.run is not None:
        report_run(result.run)
    for note in result.notes:
        emit(f"  note: {note}")
    emit()


def write_json(path: Path, baseline: PytestRun, results: Sequence[MutantResult]) -> None:
    def run_data(run: PytestRun | None) -> dict[str, object] | None:
        if run is None:
            return None
        return {
            "command": run.command,
            "returncode": run.returncode,
            "duration_seconds": run.duration,
            "timed_out": run.timed_out,
            "session": run.session,
            "collected": run.collected,
            "nodes": {
                nodeid: {
                    "phases": node.phases,
                    "exception": node.exception,
                    "exception_module": node.exception_module,
                    "message": node.message,
                    "wasxfail": node.wasxfail,
                }
                for nodeid, node in run.nodes.items()
            },
            "problems": run.problems,
        }

    document = {
        "baseline": run_data(baseline),
        "mutants": [
            {
                "id": result.mutant.mutant_id,
                "title": result.mutant.title,
                "file": result.mutant.file,
                "anchor": result.mutant.anchor,
                "replacement": result.mutant.replacement,
                "status": result.status,
                "notes": result.notes,
                "original_sha256": result.original_sha256,
                "mutated_sha256": result.mutated_sha256,
                "anchor_count": result.anchor_count,
                "probe": None
                if result.probe is None
                else {
                    "command": result.probe.command,
                    "ok": result.probe.ok,
                    "data": result.probe.data,
                    "problems": result.probe.problems,
                },
                "expected_failures": result.expected_failures,
                "assertion_failures": result.assertion_failures,
                "run": run_data(result.run),
            }
            for result in results
        ],
    }
    path.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #


def parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Kill the eight prescribed Actseal gate mutations on temporary copies.",
        allow_abbrev=False,
    )
    parser.add_argument("--only", action="append", default=[], help="run only this mutant id")
    parser.add_argument("--json", type=Path, default=None, help="write a machine-readable report")
    parser.add_argument(
        "--workdir",
        type=Path,
        default=None,
        help=(
            "existing parent directory; the run creates and removes its own uniquely named "
            "child beneath it (default: the system temporary directory)"
        ),
    )
    parser.add_argument(
        "--keep", action="store_true", help="keep this run's child directory (never the parent)"
    )
    parser.add_argument(
        "--timeout", type=float, default=600.0, help="seconds per pytest/probe subprocess"
    )
    return parser.parse_args(argv)


def select_mutants(only: Sequence[str]) -> tuple[Mutant, ...]:
    if not only:
        return MUTANTS
    wanted = set(only)
    unknown = wanted - {mutant.mutant_id for mutant in MUTANTS}
    if unknown:
        raise HarnessError(f"unknown mutant id(s): {sorted(unknown)}")
    return tuple(mutant for mutant in MUTANTS if mutant.mutant_id in wanted)


def run_baseline(
    workdir: Path, mutants: Sequence[Mutant], timeout: float
) -> tuple[PytestRun, ProbeResult]:
    tree = make_tree(workdir, "baseline")
    probe = run_probe(tree, timeout=timeout)
    run = run_pytest(tree, all_designated_tests(mutants), timeout=timeout)
    return run, probe


def execute(args: argparse.Namespace, mutants: Sequence[Mutant], workdir: Path) -> int:
    """Baseline gate, every selected mutant, the report and the final verdict."""
    before = tracked_source_digest()
    emit(f"repository: {REPO}")
    emit(f"temporary root (owned by this run): {workdir}")
    emit(f"interpreter: {sys.executable}")
    emit()
    baseline, probe = run_baseline(workdir, mutants, args.timeout)
    emit("BASELINE (unmutated temporary copy)")
    emit(f"  probe command: {probe.command}")
    emit(f"  probe fingerprint: {probe.data.get('fingerprint', '-')}")
    for problem in probe.problems:
        emit(f"  probe problem: {problem}")
    report_run(baseline)
    problems = check_baseline(baseline, mutants) + probe.problems
    if problems:
        for problem in problems:
            emit(f"  HARNESS ERROR: {problem}")
        emit("\nRESULT: harness ERROR (baseline gate failed); no mutant was judged")
        return EXIT_HARNESS_ERROR
    emit("  baseline gate: every designated node passed setup/call/teardown\n")
    results = [
        run_mutant(workdir, mutant, probe.data.get("fingerprint"), args.timeout)
        for mutant in mutants
    ]
    for result in results:
        report_mutant(result)
    if args.json is not None:
        write_json(args.json, baseline, results)
        emit(f"json report: {args.json}")
    if tracked_source_digest() != before:
        emit("HARNESS ERROR: tracked source changed during the run")
        return EXIT_HARNESS_ERROR
    emit("tracked source unchanged (SHA-256 of every copied file re-verified)")
    counts = dict.fromkeys(("KILLED", "SURVIVED", "INVALID", "UNEXECUTED"), 0)
    for result in results:
        counts[result.status] = counts.get(result.status, 0) + 1
    emit(
        "RESULT: "
        + ", ".join(f"{count} {status.lower()}" for status, count in counts.items())
        + f" of {len(mutants)} mutant(s)"
    )
    missing = [mutant.mutant_id for mutant in MUTANTS if mutant not in mutants]
    if missing:
        emit(f"not selected this run: {', '.join(missing)}")
    if counts["KILLED"] != len(mutants) or (not args.only and len(mutants) != len(MUTANTS)):
        return EXIT_NOT_KILLED
    return EXIT_OK


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    mutants = select_mutants(args.only)
    refuse_symlinks(REPO)
    return run_in_owned_workdir(
        args.workdir,
        keep=args.keep,
        repo=REPO,
        body=lambda workdir: execute(args, mutants, workdir),
    )


if __name__ == "__main__":
    try:
        sys.exit(main())
    except HarnessError as error:
        emit(f"HARNESS ERROR: {error}")
        sys.exit(EXIT_HARNESS_ERROR)
